//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEmpSys.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tEmployee
    {
        public int fId { get; set; }
        [DisplayName("員工編號")]
        [StringLength(5, ErrorMessage = "必須五個字元", MinimumLength = 5)]
        [Required]
        public string fEmpId { get; set; }
        [DisplayName("姓名")]
        [Required]
        public string fName { get; set; }
        [DisplayName("電話")]
        [Required]
        public string fPhone { get; set; }
        [DisplayName("薪資")]
        [Required]
        [Range(22000, 50000, ErrorMessage = "22000~50000")]
        public Nullable<int> fSalary { get; set; }
        [DisplayName("雇用日期")]
        [Required]
        public string fDate { get; set; }
        [DisplayName("信箱")]
        [Required]
        [EmailAddress(ErrorMessage = "必須符合信箱格式")]
        public string fEmail { get; set; }
    }
}
